name: BuildJet CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204 # Example runner, use one of BuildJet's available runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
